name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk python3-pip build-essential libssl-dev libffi-dev libsqlite3-dev zlib1g-dev unzip wget
        pip install --upgrade pip
        pip install buildozer
        pip install cython

    - name: Set up Android SDK and NDK
      run: |
        # Install Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O android-sdk.zip
        unzip android-sdk.zip -d $HOME/android-sdk

        # Move cmdline-tools to the correct folder
        mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools-old
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/android-sdk/cmdline-tools-old/* $HOME/android-sdk/cmdline-tools/latest/

        # Add sdkmanager to PATH
        export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH

        # Install platform-tools, build-tools (with AIDL), and necessary NDK version
        yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk;21.4.7075529"

        # Verify installation
        sdkmanager --list

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE  # Navigate to the repository's workspace directory
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Expense-Tracker-APK
        path: $GITHUB_WORKSPACE/bin/*.apk
